In [1]:
!sudo apt-get update
!sudo apt-get install -qq octave octave-signal liboctave-dev

!pip install matpower matpowercaseframes oct2py

Hit:1 http://archive.ubuntu.com/ubuntu bionic InRelease
Hit:2 http://archive.ubuntu.com/ubuntu bionic-updates InRelease
Hit:3 http://archive.ubuntu.com/ubuntu bionic-backports InRelease
Hit:4 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64  InRelease
Hit:5 https://cloud.r-project.org/bin/linux/ubuntu bionic-cran40/ InRelease
Hit:6 http://security.ubuntu.com/ubuntu bionic-security InRelease
Hit:7 http://ppa.launchpad.net/c2d4u.team/c2d4u4.0+/ubuntu bionic InRelease
Hit:8 http://ppa.launchpad.net/cran/libgit2/ubuntu bionic InRelease
Ign:9 https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1804/x86_64  InRelease
Hit:10 http://ppa.launchpad.net/deadsnakes/ppa/ubuntu bionic InRelease
Hit:11 https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1804/x86_64  Release
Hit:12 http://ppa.launchpad.net/graphics-drivers/ppa/ubuntu bionic InRelease
Reading package lists... Done
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: matpower in /usr/local/lib/python3.7/dist-packages (7.1.0.2.1.3)
Requirement already satisfied: matpowercaseframes in /usr/local/lib/python3.7/dist-packages (0.0.1a3)
Requirement already satisfied: oct2py in /usr/local/lib/python3.7/dist-packages (5.5.1)
Requirement already satisfied: pandas>=1.0.0 in /usr/local/lib/python3.7/dist-packages (from matpowercaseframes) (1.3.5)
Requirement already satisfied: numpy>=1.12 in /usr/local/lib/python3.7/dist-packages (from matpowercaseframes) (1.21.6)
Requirement already satisfied: pytz>=2017.3 in /usr/local/lib/python3.7/dist-packages (from pandas>=1.0.0->matpowercaseframes) (2022.1)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.7/dist-packages (from pandas>=1.0.0->matpowercaseframes) (2.8.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.7/dist-packages (from python-dateutil>=2.7.3->pandas>=1.0.0->matpowercaseframes) (1.15.0)
Requirement already satisfied: scipy>=0.17 in /usr/local/lib/python3.7/dist-packages (from oct2py) (1.7.3)
Requirement already satisfied: octave-kernel>=0.34.0 in /usr/local/lib/python3.7/dist-packages (from oct2py) (0.34.2)
Requirement already satisfied: ipykernel in /usr/local/lib/python3.7/dist-packages (from octave-kernel>=0.34.0->oct2py) (6.15.1)
Requirement already satisfied: jupyter-client>=4.3.0 in /usr/local/lib/python3.7/dist-packages (from octave-kernel>=0.34.0->oct2py) (7.3.4)
Requirement already satisfied: metakernel>=0.24.0 in /usr/local/lib/python3.7/dist-packages (from octave-kernel>=0.34.0->oct2py) (0.29.0)
Requirement already satisfied: jupyter-core>=4.9.2 in /usr/local/lib/python3.7/dist-packages (from jupyter-client>=4.3.0->octave-kernel>=0.34.0->oct2py) (4.11.1)
Requirement already satisfied: entrypoints in /usr/local/lib/python3.7/dist-packages (from jupyter-client>=4.3.0->octave-kernel>=0.34.0->oct2py) (0.4)
Requirement already satisfied: pyzmq>=23.0 in /usr/local/lib/python3.7/dist-packages (from jupyter-client>=4.3.0->octave-kernel>=0.34.0->oct2py) (23.2.0)
Requirement already satisfied: tornado>=6.0 in /usr/local/lib/python3.7/dist-packages (from jupyter-client>=4.3.0->octave-kernel>=0.34.0->oct2py) (6.2)
Requirement already satisfied: traitlets in /usr/local/lib/python3.7/dist-packages (from jupyter-client>=4.3.0->octave-kernel>=0.34.0->oct2py) (5.1.1)
Requirement already satisfied: nest-asyncio>=1.5.4 in /usr/local/lib/python3.7/dist-packages (from jupyter-client>=4.3.0->octave-kernel>=0.34.0->oct2py) (1.5.5)
Requirement already satisfied: jedi>=0.18 in /usr/local/lib/python3.7/dist-packages (from metakernel>=0.24.0->octave-kernel>=0.34.0->oct2py) (0.18.1)
Requirement already satisfied: pexpect>=4.8 in /usr/local/lib/python3.7/dist-packages (from metakernel>=0.24.0->octave-kernel>=0.34.0->oct2py) (4.8.0)
Requirement already satisfied: psutil in /usr/local/lib/python3.7/dist-packages (from ipykernel->octave-kernel>=0.34.0->oct2py) (5.4.8)
Requirement already satisfied: debugpy>=1.0 in /usr/local/lib/python3.7/dist-packages (from ipykernel->octave-kernel>=0.34.0->oct2py) (1.0.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.7/dist-packages (from ipykernel->octave-kernel>=0.34.0->oct2py) (21.3)
Requirement already satisfied: ipython>=7.23.1 in /usr/local/lib/python3.7/dist-packages (from ipykernel->octave-kernel>=0.34.0->oct2py) (7.34.0)
Requirement already satisfied: matplotlib-inline>=0.1 in /usr/local/lib/python3.7/dist-packages (from ipykernel->octave-kernel>=0.34.0->oct2py) (0.1.3)
Requirement already satisfied: pygments in /usr/local/lib/python3.7/dist-packages (from ipython>=7.23.1->ipykernel->octave-kernel>=0.34.0->oct2py) (2.6.1)
Requirement already satisfied: setuptools>=18.5 in /usr/local/lib/python3.7/dist-packages (from ipython>=7.23.1->ipykernel->octave-kernel>=0.34.0->oct2py) (57.4.0)
Requirement already satisfied: decorator in /usr/local/lib/python3.7/dist-packages (from ipython>=7.23.1->ipykernel->octave-kernel>=0.34.0->oct2py) (4.4.2)
Requirement already satisfied: prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0 in /usr/local/lib/python3.7/dist-packages (from ipython>=7.23.1->ipykernel->octave-kernel>=0.34.0->oct2py) (3.0.30)
Requirement already satisfied: backcall in /usr/local/lib/python3.7/dist-packages (from ipython>=7.23.1->ipykernel->octave-kernel>=0.34.0->oct2py) (0.2.0)
Requirement already satisfied: pickleshare in /usr/local/lib/python3.7/dist-packages (from ipython>=7.23.1->ipykernel->octave-kernel>=0.34.0->oct2py) (0.7.5)
Requirement already satisfied: parso<0.9.0,>=0.8.0 in /usr/local/lib/python3.7/dist-packages (from jedi>=0.18->metakernel>=0.24.0->octave-kernel>=0.34.0->oct2py) (0.8.3)
Requirement already satisfied: ptyprocess>=0.5 in /usr/local/lib/python3.7/dist-packages (from pexpect>=4.8->metakernel>=0.24.0->octave-kernel>=0.34.0->oct2py) (0.7.0)
Requirement already satisfied: wcwidth in /usr/local/lib/python3.7/dist-packages (from prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0->ipython>=7.23.1->ipykernel->octave-kernel>=0.34.0->oct2py) (0.2.5)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /usr/local/lib/python3.7/dist-packages (from packaging->ipykernel->octave-kernel>=0.34.0->oct2py) (3.0.9)

In [2]:
import matpower

In [3]:
matpower.__version__

'7.1.0.2.1.3'

In [4]:
import os

import pandas as pd
import numpy as np

from matpower import start_instance, path_matpower
from matpowercaseframes import CaseFrames
from matpowercaseframes.constants import COLUMNS

In [5]:
path = os.path.join(path_matpower, 'data/case9.m')

In [6]:
cf = CaseFrames(path)
cf.branch

,F_BUS,T_BUS,BR_R,BR_X,BR_B,RATE_A,RATE_B,RATE_C,TAP,SHIFT,BR_STATUS,ANGMIN,ANGMAX
1,1,4,0.0000,0.0576,0.000,250,250,250,0,0,1,-360,360
2,4,5,0.0170,0.0920,0.158,250,250,250,0,0,1,-360,360
3,5,6,0.0390,0.1700,0.358,150,150,150,0,0,1,-360,360
4,3,6,0.0000,0.0586,0.000,300,300,300,0,0,1,-360,360
5,6,7,0.0119,0.1008,0.209,150,150,150,0,0,1,-360,360
6,7,8,0.0085,0.0720,0.149,250,250,250,0,0,1,-360,360
7,8,2,0.0000,0.0625,0.000,250,250,250,0,0,1,-360,360
8,8,9,0.0320,0.1610,0.306,250,250,250,0,0,1,-360,360
9,9,4,0.0100,0.0850,0.176,250,250,250,0,0,1,-360,360

In [7]:
m = start_instance()
sol = m.loadcase('case9', verbose=False)
pd.DataFrame(sol['branch'], columns=cf.branch.columns)

,F_BUS,T_BUS,BR_R,BR_X,BR_B,RATE_A,RATE_B,RATE_C,TAP,SHIFT,BR_STATUS,ANGMIN,ANGMAX
0,1.0,4.0,0.0000,0.0576,0.000,250.0,250.0,250.0,0.0,0.0,1.0,-360.0,360.0
1,4.0,5.0,0.0170,0.0920,0.158,250.0,250.0,250.0,0.0,0.0,1.0,-360.0,360.0
2,5.0,6.0,0.0390,0.1700,0.358,150.0,150.0,150.0,0.0,0.0,1.0,-360.0,360.0
3,3.0,6.0,0.0000,0.0586,0.000,300.0,300.0,300.0,0.0,0.0,1.0,-360.0,360.0
4,6.0,7.0,0.0119,0.1008,0.209,150.0,150.0,150.0,0.0,0.0,1.0,-360.0,360.0
5,7.0,8.0,0.0085,0.0720,0.149,250.0,250.0,250.0,0.0,0.0,1.0,-360.0,360.0
6,8.0,2.0,0.0000,0.0625,0.000,250.0,250.0,250.0,0.0,0.0,1.0,-360.0,360.0
7,8.0,9.0,0.0320,0.1610,0.306,250.0,250.0,250.0,0.0,0.0,1.0,-360.0,360.0
8,9.0,4.0,0.0100,0.0850,0.176,250.0,250.0,250.0,0.0,0.0,1.0,-360.0,360.0

In [8]:
new_branch = sol['branch'][2]  # copy third branch
new_branch[COLUMNS['branch'].index('T_BUS')] = 8  # connect to bus 8
sol['branch'] = np.vstack((sol['branch'], new_branch))
pd.DataFrame(sol['branch'], columns=cf.branch.columns)

,F_BUS,T_BUS,BR_R,BR_X,BR_B,RATE_A,RATE_B,RATE_C,TAP,SHIFT,BR_STATUS,ANGMIN,ANGMAX
0,1.0,4.0,0.0000,0.0576,0.000,250.0,250.0,250.0,0.0,0.0,1.0,-360.0,360.0
1,4.0,5.0,0.0170,0.0920,0.158,250.0,250.0,250.0,0.0,0.0,1.0,-360.0,360.0
2,5.0,8.0,0.0390,0.1700,0.358,150.0,150.0,150.0,0.0,0.0,1.0,-360.0,360.0
3,3.0,6.0,0.0000,0.0586,0.000,300.0,300.0,300.0,0.0,0.0,1.0,-360.0,360.0
4,6.0,7.0,0.0119,0.1008,0.209,150.0,150.0,150.0,0.0,0.0,1.0,-360.0,360.0
5,7.0,8.0,0.0085,0.0720,0.149,250.0,250.0,250.0,0.0,0.0,1.0,-360.0,360.0
6,8.0,2.0,0.0000,0.0625,0.000,250.0,250.0,250.0,0.0,0.0,1.0,-360.0,360.0
7,8.0,9.0,0.0320,0.1610,0.306,250.0,250.0,250.0,0.0,0.0,1.0,-360.0,360.0
8,9.0,4.0,0.0100,0.0850,0.176,250.0,250.0,250.0,0.0,0.0,1.0,-360.0,360.0
9,5.0,8.0,0.0390,0.1700,0.358,150.0,150.0,150.0,0.0,0.0,1.0,-360.0,360.0

In [9]:
mpc = m.runpf(sol, verbose=True)

OSQP Error!

MATPOWER Version 7.1, 08-Oct-2020 -- AC Power Flow (Newton)

Newton's method power flow (power balance, polar) converged in 4 iterations.

Converged in 0.04 seconds
================================================================================
|     System Summary                                                           |
================================================================================

How many?                How much?              P (MW)            Q (MVAr)
---------------------    -------------------  -------------  -----------------
Buses              9     Total Gen Capacity     820.0        -900.0 to 900.0
Generators         3     On-line Capacity       820.0        -900.0 to 900.0
Committed Gens     3     Generation (actual)    318.8             -22.7
Loads              3     Load                   315.0             115.0
  Fixed            3       Fixed                315.0             115.0
  Dispatchable     0       Dispatchable          -0.0 of -0.0      -0.0
Shunts             0     Shunt (inj)             -0.0               0.0
Branches          10     Losses (I^2 * Z)         3.81             45.58
Transformers       0     Branch Charging (inj)     -              183.3
Inter-ties         0     Total Inter-tie Flow     0.0               0.0
Areas              1

                          Minimum                      Maximum
                 -------------------------  --------------------------------
Voltage Magnitude   1.012 p.u. @ bus 9          1.043 p.u. @ bus 8
Voltage Angle      -4.79 deg   @ bus 9          7.79 deg   @ bus 3
P Losses (I^2*R)             -                  1.37 MW    @ line 8-9
Q Losses (I^2*X)             -                 16.09 MVAr  @ line 8-2

================================================================================
|     Bus Data                                                                 |
================================================================================
 Bus      Voltage          Generation             Load
  #   Mag(pu) Ang(deg)   P (MW)   Q (MVAr)   P (MW)   Q (MVAr)
----- ------- --------  --------  --------  --------  --------
    1  1.040    0.000*    70.81      7.01       -         -
    2  1.025    6.399    163.00    -21.87       -         -
    3  1.025    7.790     85.00     -7.83       -         -
    4  1.037   -2.168       -         -         -         -
    5  1.038   -2.753       -         -       90.00     30.00
    6  1.031    5.087       -         -         -         -
    7  1.025    0.430       -         -      100.00     35.00
    8  1.043    0.931       -         -         -         -
    9  1.012   -4.789       -         -      125.00     50.00
                        --------  --------  --------  --------
               Total:    318.81    -22.69    315.00    115.00

================================================================================
|     Branch Data                                                              |
================================================================================
Brnch   From   To    From Bus Injection   To Bus Injection     Loss (I^2 * Z)
  #     Bus    Bus    P (MW)   Q (MVAr)   P (MW)   Q (MVAr)   P (MW)   Q (MVAr)
-----  -----  -----  --------  --------  --------  --------  --------  --------
   1      1      4     70.81      7.01    -70.81     -4.32    -0.000      2.70
   2      4      5     11.41    -11.41    -11.39     -5.47     0.022      0.12
   3      5      8    -39.30    -12.27     39.88    -23.96     0.577      2.52
   4      3      6     85.00     -7.83    -85.00     11.90     0.000      4.06
   5      6      7     85.00    -11.90    -84.19     -3.32     0.810      6.86
   6      7      8    -15.81    -31.68     15.88     16.31     0.066      0.56
   7      8      2   -163.00     37.96    163.00    -21.87     0.000     16.09
   8      8      9     67.36     -6.34    -66.00    -19.09     1.366      6.87
   9      9      4    -59.00    -30.91     59.39     15.73     0.387      3.29
  10      5      8    -39.30    -12.27     39.88    -23.96     0.577      2.52
                                                             --------  --------
                                                    Total:     3.805     45.58

In [10]:
pd.DataFrame(mpc['branch'], columns=COLUMNS['branch'][:17])

,F_BUS,T_BUS,BR_R,BR_X,BR_B,RATE_A,RATE_B,RATE_C,TAP,SHIFT,BR_STATUS,ANGMIN,ANGMAX,PF,QF,PT,QT
0,1.0,4.0,0.0000,0.0576,0.000,250.0,250.0,250.0,0.0,0.0,1.0,-360.0,360.0,70.805365,7.014062,-70.805365,-4.318005
1,4.0,5.0,0.0170,0.0920,0.158,250.0,250.0,250.0,0.0,0.0,1.0,-360.0,360.0,11.414546,-11.413209,-11.392595,-5.466825
2,5.0,8.0,0.0390,0.1700,0.358,150.0,150.0,150.0,0.0,0.0,1.0,-360.0,360.0,-39.303703,-12.266587,39.881041,-23.964865
3,3.0,6.0,0.0000,0.0586,0.000,300.0,300.0,300.0,0.0,0.0,1.0,-360.0,360.0,85.000000,-7.834303,-85.000000,11.898376
4,6.0,7.0,0.0119,0.1008,0.209,150.0,150.0,150.0,0.0,0.0,1.0,-360.0,360.0,85.000000,-11.898376,-84.190491,-3.322999
5,7.0,8.0,0.0085,0.0720,0.149,250.0,250.0,250.0,0.0,0.0,1.0,-360.0,360.0,-15.809509,-31.677001,15.875754,16.305610
6,8.0,2.0,0.0000,0.0625,0.000,250.0,250.0,250.0,0.0,0.0,1.0,-360.0,360.0,-163.000000,37.959322,163.000000,-21.869335
7,8.0,9.0,0.0320,0.1610,0.306,250.0,250.0,250.0,0.0,0.0,1.0,-360.0,360.0,67.362164,-6.335202,-65.996308,-19.094531
8,9.0,4.0,0.0100,0.0850,0.176,250.0,250.0,250.0,0.0,0.0,1.0,-360.0,360.0,-59.003692,-30.905469,59.390819,15.731214
9,5.0,8.0,0.0390,0.1700,0.358,150.0,150.0,150.0,0.0,0.0,1.0,-360.0,360.0,-39.303703,-12.266587,39.881041,-23.964865