In [ ]:
# install octave
!sudo apt-get -qq update
!sudo apt-get -qq install octave octave-signal liboctave-dev

# # install oct2py that compatible with colab
# google-colab 1.0.0 requires ipykernel~=5.3.4.
# google-colab 1.0.0 requires ipython~=7.9.0.
# google-colab 1.0.0 requires tornado~=6.0.4.
!pip install --quiet ipykernel==5.3.4 ipython==7.9.0 tornado==6.0.4 oct2py

# install packages
!pip install matpower matpowercaseframes --quiet

In [ ]:
import oct2py
import matpower

print(f"oct2py version: {oct2py.__version__}")
print(f"matpower version: {matpower.__version__}")

oct2py version: 5.6.0
matpower version: 7.1.0.2.1.4

In [ ]:
import os

import pandas as pd
import numpy as np

from matpower import start_instance, path_matpower
from matpowercaseframes import CaseFrames
from matpowercaseframes.constants import COLUMNS

## Inspect data

In [ ]:
path = os.path.join(path_matpower, 'data/case9.m')

In [ ]:
cf = CaseFrames(path)
cf.branch

,F_BUS,T_BUS,BR_R,BR_X,BR_B,RATE_A,RATE_B,RATE_C,TAP,SHIFT,BR_STATUS,ANGMIN,ANGMAX
1,1,4,0.0000,0.0576,0.000,250,250,250,0,0,1,-360,360
2,4,5,0.0170,0.0920,0.158,250,250,250,0,0,1,-360,360
3,5,6,0.0390,0.1700,0.358,150,150,150,0,0,1,-360,360
4,3,6,0.0000,0.0586,0.000,300,300,300,0,0,1,-360,360
5,6,7,0.0119,0.1008,0.209,150,150,150,0,0,1,-360,360
6,7,8,0.0085,0.0720,0.149,250,250,250,0,0,1,-360,360
7,8,2,0.0000,0.0625,0.000,250,250,250,0,0,1,-360,360
8,8,9,0.0320,0.1610,0.306,250,250,250,0,0,1,-360,360
9,9,4,0.0100,0.0850,0.176,250,250,250,0,0,1,-360,360

In [ ]:
m = start_instance()
sol = m.loadcase('case9', verbose=False)
pd.DataFrame(sol['branch'], columns=cf.branch.columns)

,F_BUS,T_BUS,BR_R,BR_X,BR_B,RATE_A,RATE_B,RATE_C,TAP,SHIFT,BR_STATUS,ANGMIN,ANGMAX
0,1.0,4.0,0.0000,0.0576,0.000,250.0,250.0,250.0,0.0,0.0,1.0,-360.0,360.0
1,4.0,5.0,0.0170,0.0920,0.158,250.0,250.0,250.0,0.0,0.0,1.0,-360.0,360.0
2,5.0,6.0,0.0390,0.1700,0.358,150.0,150.0,150.0,0.0,0.0,1.0,-360.0,360.0
3,3.0,6.0,0.0000,0.0586,0.000,300.0,300.0,300.0,0.0,0.0,1.0,-360.0,360.0
4,6.0,7.0,0.0119,0.1008,0.209,150.0,150.0,150.0,0.0,0.0,1.0,-360.0,360.0
5,7.0,8.0,0.0085,0.0720,0.149,250.0,250.0,250.0,0.0,0.0,1.0,-360.0,360.0
6,8.0,2.0,0.0000,0.0625,0.000,250.0,250.0,250.0,0.0,0.0,1.0,-360.0,360.0
7,8.0,9.0,0.0320,0.1610,0.306,250.0,250.0,250.0,0.0,0.0,1.0,-360.0,360.0
8,9.0,4.0,0.0100,0.0850,0.176,250.0,250.0,250.0,0.0,0.0,1.0,-360.0,360.0

## Run base

In [ ]:
mpc = m.runpf(sol, verbose=True)

MATPOWER Version 7.1, 08-Oct-2020 -- AC Power Flow (Newton)

Newton's method power flow (power balance, polar) converged in 4 iterations.

Converged in 0.03 seconds
================================================================================
|     System Summary                                                           |
================================================================================

How many?                How much?              P (MW)            Q (MVAr)
---------------------    -------------------  -------------  -----------------
Buses              9     Total Gen Capacity     820.0        -900.0 to 900.0
Generators         3     On-line Capacity       820.0        -900.0 to 900.0
Committed Gens     3     Generation (actual)    319.6              22.8
Loads              3     Load                   315.0             115.0
  Fixed            3       Fixed                315.0             115.0
  Dispatchable     0       Dispatchable          -0.0 of -0.0      -0.0
Shunts             0     Shunt (inj)             -0.0               0.0
Branches           9     Losses (I^2 * Z)         4.64             48.38
Transformers       0     Branch Charging (inj)     -              140.5
Inter-ties         0     Total Inter-tie Flow     0.0               0.0
Areas              1

                          Minimum                      Maximum
                 -------------------------  --------------------------------
Voltage Magnitude   0.996 p.u. @ bus 9          1.040 p.u. @ bus 1
Voltage Angle      -3.99 deg   @ bus 9          9.28 deg   @ bus 2
P Losses (I^2*R)             -                  2.30 MW    @ line 8-9
Q Losses (I^2*X)             -                 15.83 MVAr  @ line 8-2

================================================================================
|     Bus Data                                                                 |
================================================================================
 Bus      Voltage          Generation             Load
  #   Mag(pu) Ang(deg)   P (MW)   Q (MVAr)   P (MW)   Q (MVAr)
----- ------- --------  --------  --------  --------  --------
    1  1.040    0.000*    71.64     27.05       -         -
    2  1.025    9.280    163.00      6.65       -         -
    3  1.025    4.665     85.00    -10.86       -         -
    4  1.026   -2.217       -         -         -         -
    5  1.013   -3.687       -         -       90.00     30.00
    6  1.032    1.967       -         -         -         -
    7  1.016    0.728       -         -      100.00     35.00
    8  1.026    3.720       -         -         -         -
    9  0.996   -3.989       -         -      125.00     50.00
                        --------  --------  --------  --------
               Total:    319.64     22.84    315.00    115.00

================================================================================
|     Branch Data                                                              |
================================================================================
Brnch   From   To    From Bus Injection   To Bus Injection     Loss (I^2 * Z)
  #     Bus    Bus    P (MW)   Q (MVAr)   P (MW)   Q (MVAr)   P (MW)   Q (MVAr)
-----  -----  -----  --------  --------  --------  --------  --------  --------
   1      1      4     71.64     27.05    -71.64    -23.92     0.000      3.12
   2      4      5     30.70      1.03    -30.54    -16.54     0.166      0.90
   3      5      6    -59.46    -13.46     60.82    -18.07     1.354      5.90
   4      3      6     85.00    -10.86    -85.00     14.96     0.000      4.10
   5      6      7     24.18      3.12    -24.10    -24.30     0.088      0.75
   6      7      8    -75.90    -10.70     76.38     -0.80     0.475      4.03
   7      8      2   -163.00      9.18    163.00      6.65     0.000     15.83
   8      8      9     86.62     -8.38    -84.32    -11.31     2.300     11.57
   9      9      4    -40.68    -38.69     40.94     22.89     0.258      2.19
                                                             --------  --------
                                                    Total:     4.641     48.38

## Copy and editing branch

In [ ]:
new_branch = sol['branch'][2].copy()  # copy third branch, must use .copy()
new_branch[COLUMNS['branch'].index('T_BUS')] = 8  # connect to bus 8
sol['branch'] = np.vstack((sol['branch'], new_branch))
pd.DataFrame(sol['branch'], columns=cf.branch.columns)

,F_BUS,T_BUS,BR_R,BR_X,BR_B,RATE_A,RATE_B,RATE_C,TAP,SHIFT,BR_STATUS,ANGMIN,ANGMAX
0,1.0,4.0,0.0000,0.0576,0.000,250.0,250.0,250.0,0.0,0.0,1.0,-360.0,360.0
1,4.0,5.0,0.0170,0.0920,0.158,250.0,250.0,250.0,0.0,0.0,1.0,-360.0,360.0
2,5.0,6.0,0.0390,0.1700,0.358,150.0,150.0,150.0,0.0,0.0,1.0,-360.0,360.0
3,3.0,6.0,0.0000,0.0586,0.000,300.0,300.0,300.0,0.0,0.0,1.0,-360.0,360.0
4,6.0,7.0,0.0119,0.1008,0.209,150.0,150.0,150.0,0.0,0.0,1.0,-360.0,360.0
5,7.0,8.0,0.0085,0.0720,0.149,250.0,250.0,250.0,0.0,0.0,1.0,-360.0,360.0
6,8.0,2.0,0.0000,0.0625,0.000,250.0,250.0,250.0,0.0,0.0,1.0,-360.0,360.0
7,8.0,9.0,0.0320,0.1610,0.306,250.0,250.0,250.0,0.0,0.0,1.0,-360.0,360.0
8,9.0,4.0,0.0100,0.0850,0.176,250.0,250.0,250.0,0.0,0.0,1.0,-360.0,360.0
9,5.0,8.0,0.0390,0.1700,0.358,150.0,150.0,150.0,0.0,0.0,1.0,-360.0,360.0

In [ ]:
mpc = m.runpf(sol, verbose=True)

MATPOWER Version 7.1, 08-Oct-2020 -- AC Power Flow (Newton)

Newton's method power flow (power balance, polar) converged in 4 iterations.

Converged in 0.03 seconds
================================================================================
|     System Summary                                                           |
================================================================================

How many?                How much?              P (MW)            Q (MVAr)
---------------------    -------------------  -------------  -----------------
Buses              9     Total Gen Capacity     820.0        -900.0 to 900.0
Generators         3     On-line Capacity       820.0        -900.0 to 900.0
Committed Gens     3     Generation (actual)    318.5             -24.8
Loads              3     Load                   315.0             115.0
  Fixed            3       Fixed                315.0             115.0
  Dispatchable     0       Dispatchable          -0.0 of -0.0      -0.0
Shunts             0     Shunt (inj)             -0.0               0.0
Branches          10     Losses (I^2 * Z)         3.45             42.55
Transformers       0     Branch Charging (inj)     -              182.3
Inter-ties         0     Total Inter-tie Flow     0.0               0.0
Areas              1

                          Minimum                      Maximum
                 -------------------------  --------------------------------
Voltage Magnitude   1.008 p.u. @ bus 9          1.040 p.u. @ bus 1
Voltage Angle      -4.80 deg   @ bus 9          6.47 deg   @ bus 2
P Losses (I^2*R)             -                  1.36 MW    @ line 8-9
Q Losses (I^2*X)             -                 15.91 MVAr  @ line 8-2

================================================================================
|     Bus Data                                                                 |
================================================================================
 Bus      Voltage          Generation             Load
  #   Mag(pu) Ang(deg)   P (MW)   Q (MVAr)   P (MW)   Q (MVAr)
----- ------- --------  --------  --------  --------  --------
    1  1.040    0.000*    70.45     10.60       -         -
    2  1.025    6.467    163.00    -13.04       -         -
    3  1.025    3.823     85.00    -22.33       -         -
    4  1.035   -2.161       -         -         -         -
    5  1.034   -2.702       -         -       90.00     30.00
    6  1.039    1.142       -         -         -         -
    7  1.026   -1.175       -         -      100.00     35.00
    8  1.038    0.971       -         -         -         -
    9  1.008   -4.799       -         -      125.00     50.00
                        --------  --------  --------  --------
               Total:    318.45    -24.77    315.00    115.00

================================================================================
|     Branch Data                                                              |
================================================================================
Brnch   From   To    From Bus Injection   To Bus Injection     Loss (I^2 * Z)
  #     Bus    Bus    P (MW)   Q (MVAr)   P (MW)   Q (MVAr)   P (MW)   Q (MVAr)
-----  -----  -----  --------  --------  --------  --------  --------  --------
   1      1      4     70.45     10.60    -70.45     -7.90     0.000      2.70
   2      4      5     10.81     -9.44    -10.79     -7.37     0.019      0.10
   3      5      6    -40.58    -11.39     41.20    -24.36     0.623      2.71
   4      3      6     85.00    -22.33    -85.00     26.63     0.000      4.31
   5      6      7     43.80     -2.28    -43.57    -18.13     0.220      1.87
   6      7      8    -56.43    -16.87     56.69      3.23     0.264      2.23
   7      8      2   -163.00     28.95    163.00    -13.04    -0.000     15.91
   8      8      9     67.12     -7.49    -65.75    -17.69     1.363      6.86
   9      9      4    -59.25    -32.31     59.64     17.34     0.399      3.39
  10      5      8    -38.63    -11.24     39.19    -24.70     0.567      2.47
                                                             --------  --------
                                                    Total:     3.454     42.55

In [ ]:
pd.DataFrame(mpc['branch'], columns=COLUMNS['branch'][:17])

,F_BUS,T_BUS,BR_R,BR_X,BR_B,RATE_A,RATE_B,RATE_C,TAP,SHIFT,BR_STATUS,ANGMIN,ANGMAX,PF,QF,PT,QT
0,1.0,4.0,0.0000,0.0576,0.000,250.0,250.0,250.0,0.0,0.0,1.0,-360.0,360.0,70.454094,10.603728,-70.454094,-7.900417
1,4.0,5.0,0.0170,0.0920,0.158,250.0,250.0,250.0,0.0,0.0,1.0,-360.0,360.0,10.809598,-9.436561,-10.790898,-7.369035
2,5.0,6.0,0.0390,0.1700,0.358,150.0,150.0,150.0,0.0,0.0,1.0,-360.0,360.0,-40.582184,-11.386880,41.204848,-24.356641
3,3.0,6.0,0.0000,0.0586,0.000,300.0,300.0,300.0,0.0,0.0,1.0,-360.0,360.0,85.000000,-22.326555,-85.000000,26.634426
4,6.0,7.0,0.0119,0.1008,0.209,150.0,150.0,150.0,0.0,0.0,1.0,-360.0,360.0,43.795152,-2.277785,-43.574748,-18.134364
5,7.0,8.0,0.0085,0.0720,0.149,250.0,250.0,250.0,0.0,0.0,1.0,-360.0,360.0,-56.425252,-16.865636,56.688913,3.234035
6,8.0,2.0,0.0000,0.0625,0.000,250.0,250.0,250.0,0.0,0.0,1.0,-360.0,360.0,-163.000000,28.950311,163.000000,-13.043626
7,8.0,9.0,0.0320,0.1610,0.306,250.0,250.0,250.0,0.0,0.0,1.0,-360.0,360.0,67.117183,-7.485969,-65.754557,-17.686006
8,9.0,4.0,0.0100,0.0850,0.176,250.0,250.0,250.0,0.0,0.0,1.0,-360.0,360.0,-59.245443,-32.313994,59.644496,17.336977
9,5.0,8.0,0.0390,0.1700,0.358,150.0,150.0,150.0,0.0,0.0,1.0,-360.0,360.0,-38.626918,-11.244085,39.193903,-24.698376