In [2]:
!sudo apt-get update
!sudo apt-get install -qq octave octave-signal liboctave-dev

!pip install matpower matpowercaseframes oct2py

Hit:1 http://security.ubuntu.com/ubuntu bionic-security InRelease
Hit:2 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64  InRelease
Hit:3 https://cloud.r-project.org/bin/linux/ubuntu bionic-cran40/ InRelease
Hit:4 http://archive.ubuntu.com/ubuntu bionic InRelease
Hit:5 http://ppa.launchpad.net/c2d4u.team/c2d4u4.0+/ubuntu bionic InRelease
Hit:6 http://archive.ubuntu.com/ubuntu bionic-updates InRelease
Hit:7 http://archive.ubuntu.com/ubuntu bionic-backports InRelease
Hit:8 http://ppa.launchpad.net/cran/libgit2/ubuntu bionic InRelease
Ign:9 https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1804/x86_64  InRelease
Hit:10 https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1804/x86_64  Release
Hit:11 http://ppa.launchpad.net/deadsnakes/ppa/ubuntu bionic InRelease
Hit:12 http://ppa.launchpad.net/graphics-drivers/ppa/ubuntu bionic InRelease
Reading package lists... Done
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: matpower in /usr/local/lib/python3.7/dist-packages (7.1.0.2.1.3)
Requirement already satisfied: matpowercaseframes in /usr/local/lib/python3.7/dist-packages (0.0.1a3)
Requirement already satisfied: oct2py in /usr/local/lib/python3.7/dist-packages (5.5.1)
Requirement already satisfied: pandas>=1.0.0 in /usr/local/lib/python3.7/dist-packages (from matpowercaseframes) (1.3.5)
Requirement already satisfied: numpy>=1.12 in /usr/local/lib/python3.7/dist-packages (from matpowercaseframes) (1.21.6)
Requirement already satisfied: pytz>=2017.3 in /usr/local/lib/python3.7/dist-packages (from pandas>=1.0.0->matpowercaseframes) (2022.1)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.7/dist-packages (from pandas>=1.0.0->matpowercaseframes) (2.8.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.7/dist-packages (from python-dateutil>=2.7.3->pandas>=1.0.0->matpowercaseframes) (1.15.0)
Requirement already satisfied: octave-kernel>=0.34.0 in /usr/local/lib/python3.7/dist-packages (from oct2py) (0.34.2)
Requirement already satisfied: scipy>=0.17 in /usr/local/lib/python3.7/dist-packages (from oct2py) (1.5.4)
Requirement already satisfied: jupyter-client>=4.3.0 in /usr/local/lib/python3.7/dist-packages (from octave-kernel>=0.34.0->oct2py) (7.3.4)
Requirement already satisfied: ipykernel in /usr/local/lib/python3.7/dist-packages (from octave-kernel>=0.34.0->oct2py) (6.15.1)
Requirement already satisfied: metakernel>=0.24.0 in /usr/local/lib/python3.7/dist-packages (from octave-kernel>=0.34.0->oct2py) (0.29.0)
Requirement already satisfied: nest-asyncio>=1.5.4 in /usr/local/lib/python3.7/dist-packages (from jupyter-client>=4.3.0->octave-kernel>=0.34.0->oct2py) (1.5.5)
Requirement already satisfied: entrypoints in /usr/local/lib/python3.7/dist-packages (from jupyter-client>=4.3.0->octave-kernel>=0.34.0->oct2py) (0.4)
Requirement already satisfied: pyzmq>=23.0 in /usr/local/lib/python3.7/dist-packages (from jupyter-client>=4.3.0->octave-kernel>=0.34.0->oct2py) (23.2.0)
Requirement already satisfied: jupyter-core>=4.9.2 in /usr/local/lib/python3.7/dist-packages (from jupyter-client>=4.3.0->octave-kernel>=0.34.0->oct2py) (4.11.1)
Requirement already satisfied: tornado>=6.0 in /usr/local/lib/python3.7/dist-packages (from jupyter-client>=4.3.0->octave-kernel>=0.34.0->oct2py) (6.2)
Requirement already satisfied: traitlets in /usr/local/lib/python3.7/dist-packages (from jupyter-client>=4.3.0->octave-kernel>=0.34.0->oct2py) (5.1.1)
Requirement already satisfied: pexpect>=4.8 in /usr/local/lib/python3.7/dist-packages (from metakernel>=0.24.0->octave-kernel>=0.34.0->oct2py) (4.8.0)
Requirement already satisfied: jedi>=0.18 in /usr/local/lib/python3.7/dist-packages (from metakernel>=0.24.0->octave-kernel>=0.34.0->oct2py) (0.18.1)
Requirement already satisfied: debugpy>=1.0 in /usr/local/lib/python3.7/dist-packages (from ipykernel->octave-kernel>=0.34.0->oct2py) (1.0.0)
Requirement already satisfied: psutil in /usr/local/lib/python3.7/dist-packages (from ipykernel->octave-kernel>=0.34.0->oct2py) (5.4.8)
Requirement already satisfied: packaging in /usr/local/lib/python3.7/dist-packages (from ipykernel->octave-kernel>=0.34.0->oct2py) (21.3)
Requirement already satisfied: ipython>=7.23.1 in /usr/local/lib/python3.7/dist-packages (from ipykernel->octave-kernel>=0.34.0->oct2py) (7.34.0)
Requirement already satisfied: matplotlib-inline>=0.1 in /usr/local/lib/python3.7/dist-packages (from ipykernel->octave-kernel>=0.34.0->oct2py) (0.1.3)
Requirement already satisfied: pygments in /usr/local/lib/python3.7/dist-packages (from ipython>=7.23.1->ipykernel->octave-kernel>=0.34.0->oct2py) (2.6.1)
Requirement already satisfied: setuptools>=18.5 in /usr/local/lib/python3.7/dist-packages (from ipython>=7.23.1->ipykernel->octave-kernel>=0.34.0->oct2py) (57.4.0)
Requirement already satisfied: backcall in /usr/local/lib/python3.7/dist-packages (from ipython>=7.23.1->ipykernel->octave-kernel>=0.34.0->oct2py) (0.2.0)
Requirement already satisfied: decorator in /usr/local/lib/python3.7/dist-packages (from ipython>=7.23.1->ipykernel->octave-kernel>=0.34.0->oct2py) (4.4.2)
Requirement already satisfied: pickleshare in /usr/local/lib/python3.7/dist-packages (from ipython>=7.23.1->ipykernel->octave-kernel>=0.34.0->oct2py) (0.7.5)
Requirement already satisfied: prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0 in /usr/local/lib/python3.7/dist-packages (from ipython>=7.23.1->ipykernel->octave-kernel>=0.34.0->oct2py) (3.0.30)
Requirement already satisfied: parso<0.9.0,>=0.8.0 in /usr/local/lib/python3.7/dist-packages (from jedi>=0.18->metakernel>=0.24.0->octave-kernel>=0.34.0->oct2py) (0.8.3)
Requirement already satisfied: ptyprocess>=0.5 in /usr/local/lib/python3.7/dist-packages (from pexpect>=4.8->metakernel>=0.24.0->octave-kernel>=0.34.0->oct2py) (0.7.0)
Requirement already satisfied: wcwidth in /usr/local/lib/python3.7/dist-packages (from prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0->ipython>=7.23.1->ipykernel->octave-kernel>=0.34.0->oct2py) (0.2.5)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /usr/local/lib/python3.7/dist-packages (from packaging->ipykernel->octave-kernel>=0.34.0->oct2py) (3.0.9)

In [3]:
import matpower

In [4]:
matpower.__version__

'7.1.0.2.1.3'

In [18]:
import os

import pandas as pd

from matpower import start_instance, path_matpower
from matpowercaseframes import CaseFrames

In [10]:
path = os.path.join(path_matpower, 'data/case9.m')

In [23]:
cf = CaseFrames(path)
cf.bus

   BUS_I  BUS_TYPE   PD  QD  GS  BS  ...  VM  VA  BASE_KV  ZONE  VMAX  VMIN
1      1         3    0   0   0   0  ...   1   0      345     1   1.1   0.9
2      2         2    0   0   0   0  ...   1   0      345     1   1.1   0.9
3      3         2    0   0   0   0  ...   1   0      345     1   1.1   0.9
4      4         1    0   0   0   0  ...   1   0      345     1   1.1   0.9
5      5         1   90  30   0   0  ...   1   0      345     1   1.1   0.9
6      6         1    0   0   0   0  ...   1   0      345     1   1.1   0.9
7      7         1  100  35   0   0  ...   1   0      345     1   1.1   0.9
8      8         1    0   0   0   0  ...   1   0      345     1   1.1   0.9
9      9         1  125  50   0   0  ...   1   0      345     1   1.1   0.9

[9 rows x 13 columns]

In [25]:
m = start_instance()
sol = m.loadcase('case9', verbose=False)
df = pd.DataFrame(sol['bus'], columns=cf.bus.columns)
df

   BUS_I  BUS_TYPE     PD    QD   GS   BS  ...   VM   VA  BASE_KV  ZONE  VMAX  VMIN
0    1.0       3.0    0.0   0.0  0.0  0.0  ...  1.0  0.0    345.0   1.0   1.1   0.9
1    2.0       2.0    0.0   0.0  0.0  0.0  ...  1.0  0.0    345.0   1.0   1.1   0.9
2    3.0       2.0    0.0   0.0  0.0  0.0  ...  1.0  0.0    345.0   1.0   1.1   0.9
3    4.0       1.0    0.0   0.0  0.0  0.0  ...  1.0  0.0    345.0   1.0   1.1   0.9
4    5.0       1.0   90.0  30.0  0.0  0.0  ...  1.0  0.0    345.0   1.0   1.1   0.9
5    6.0       1.0    0.0   0.0  0.0  0.0  ...  1.0  0.0    345.0   1.0   1.1   0.9
6    7.0       1.0  100.0  35.0  0.0  0.0  ...  1.0  0.0    345.0   1.0   1.1   0.9
7    8.0       1.0    0.0   0.0  0.0  0.0  ...  1.0  0.0    345.0   1.0   1.1   0.9
8    9.0       1.0  125.0  50.0  0.0  0.0  ...  1.0  0.0    345.0   1.0   1.1   0.9

[9 rows x 13 columns]